# Generated by Django 5.2.3 on 2025-07-20 14:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user1", "0007_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                default="defaults/avatar.png",
                max_length=255,
                verbose_name="profile_picture",
            ),
        ),
    ]
